### ISSUE TITLE
Suggestion: Show history

### ISSUE THREAD

**Issue by thisischrys** [goaaats/Dalamud.FindAnything#13]
I would love an option to show my last run commands. Preferably these show under the search box when this option is on without any further input required, and hitting enter reruns the last command.

**Comment by NadyaNayme** [comment]
What's funny is I literally just submitted this feedback via the /xlplugins -> feedback option in game. Maybe 1-2 minutes before this. Along with usage ranked commands (eg: searching "Camp" if you teleport to Camp Broken Glass the most would list that before all the other camp teleports).

Due to the close timing of the suggestions I just want to make it clear that I (Nyu#0117) did not open this issue. I trust both sources get seen and wouldn't want to come off as spammy.

**Comment by goaaats** [comment]
This is implemented now
